name: "Fork Sync"
on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:
jobs:
  sync-master:
    runs-on: ubuntu-latest
    name: "Sync from Terracotta-OSS/terracotta-platform@master"
    steps:
    - name: "Checkout: master"
      uses: actions/checkout@v2
      with:
        ref: master
        token: ${{ github.token }}
    - name: "Update: master"
      id: sync-master
      uses: mathieucarbou/Fork-Sync-With-Upstream-action@fork-sync
      with:
        domain: 'github.com'
        upstream_repository: Terracotta-OSS/terracotta-platform
        upstream_branch: master
        target_branch: master
        git_pull_args: --ff-only
        # git_push_args: --force
    - name: Timestamp
      run: date
