name: "Fork Sync"
on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:
jobs:
  sync-master:
    runs-on: ubuntu-latest
    name: "Sync from Terracotta-OSS/terracotta-platform@master"
    steps:
    - name: "Checkout: master"
      uses: actions/checkout@v2
      with:
        ref: master
        token: ${{ github.token }}
    - name: "Update: master"
      id: sync-master
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_repo: Terracotta-OSS/terracotta-platform
        upstream_sync_branch: master
        target_sync_branch: master
    - name: Timestamp
      run: date
